# Generated by Django 5.0.4 on 2024-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('weight_training', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamberger', models.IntegerField(default=0)),
                ('pizza', models.IntegerField(default=0)),
                ('chicken', models.IntegerField(default=0)),
            ],
        ),
    ]
