# Generated by Django 5.0.4 on 2024-07-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_cal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hamberger', models.IntegerField(default=0)),
                ('pizza', models.IntegerField(default=0)),
                ('chicken', models.IntegerField(default=0)),
                ('walk', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('weight_training', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
