# Generated by Django 5.0.4 on 2024-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_cal', '0002_usercal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercal',
            name='date',
            field=models.DateField(),
        ),
    ]
